# stacks/cloudflared/docker-compose.yml
version: '3.9'

services:
  cloudflared:
    image: docker.io/cloudflare/cloudflared:2024.10.1
    user: ${PUID}:${PGID}
    environment:
      TUNNEL_TOKEN: "${CLOUDFLARED_TUNNEL_TOKEN}"
      TUNNEL_METRICS: "${CLOUDFLARED_TUNNEL_METRICS}"
    command: tunnel --no-autoupdate run
    volumes:
      - type: volume
        source: cloudflared
        target: "/etc/cloudflared"
    network_mode: bridge
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: unless-stopped
      resources:
        limits:
          cpus: '1'
          memory: '256M'
        reservations:
          memory: '32M'

volumes:
  cloudflared:
    name: "cloudflared"
    driver: local
