# stacks/portainer/docker-compose.yml
version: '3.9'

services:
  portainer:
    image: docker.io/portainer/portainer-ce:lts
    user: ${PUID}:${PGID}
    ports:
      - 9000:9000/tcp
    volumes:
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
      - type: volume
        source: portainer
        target: "/data"
    network-mode: bridge
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: '256M'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  portainer:
    name: "portainer"
    driver: local
