name: Generate CHANGELOG

on:
  pull_request:
    branches: [main, develop, alpha]
    types: [closed]

jobs:
  generate-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Generate CHANGELOG.md (develop branch)
        if: github.base_ref == 'develop'
        uses: scottbrenner/generate-changelog-action@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: CHANGELOG.md
          output: markdown
          description-extraction-regex: '(?<=## Description\n\n)(.*?)(?=\n## Related Issue)' 

      - name: Generate CHANGELOG.md (main and alpha branches)
        if: github.base_ref == 'main' || github.base_ref == 'alpha'
        uses: scottbrenner/generate-changelog-action@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: CHANGELOG.md
          output: markdown

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG.md"
          git push