name: 'enforcer'

on:
  pull_request:
    branches: [main, beta, alpha, staging]

jobs:
  branch-policy-enforcement:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Flow
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]] && [[ "${{ github.head_ref }}" != "beta" ]]; then
            echo "::error::ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'beta' first."
            exit 1
          elif [[ "${{ github.base_ref }}" == "beta" ]] && [[ "${{ github.head_ref }}" != "alpha" ]]; then
            echo "::error::ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'alpha' first."
            exit 1
          elif [[ "${{ github.base_ref }}" == "alpha" ]] && [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "::error::ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Please merge to 'staging' first."
            exit 1
          elif [[ "${{ github.base_ref }}" == "staging" ]] && ! ( [[ "${{ github.head_ref }}" == "feature"* ]] || [[ "${{ github.head_ref }}" == "stack"* ]] || [[ "${{ github.head_ref }}" == "hotfix"* ]] ); then
            echo "::error::ERROR: You cannot merge to ${{ github.base_ref }} from ${{ github.head_ref }}. Branches merged into staging must start with 'feature/', 'stack/', or 'hotfix/'."
            exit 1
          fi

  pull-request-enforcement:
    runs-on: ubuntu-latest
    steps:
      - name: Validate title format
        run: |
          if [[ ! "add:stack/github-actions-runner:#14:: archived the container" =~ ^(add|remove|update):.*$ ]]; then
            echo "::error::Error: Must start with add, remove, or update."
          elif [[ ! "add:stack/github-actions-runner:#14:: archived the container" =~ ^(add|remove|update):(stack|feature|hotfix)\/.*$ ]]; then
            echo "::error::Error: Must include stack, feature, or hotfix after action."
          elif [[ ! "add:stack/github-actions-runner:#14:: archived the container" =~ ^(add|remove|update):(stack|feature|hotfix)\/([^:]+):.*$ ]]; then
            echo "::error::Error: Must include stack/feature name."
          elif [[ ! "add:stack/github-actions-runner:#14:: archived the container" =~ ^(add|remove|update):(stack|feature|hotfix)\/([^:]+):(#[0-9]+,)?::\s*\.+$ ]]; then
            echo "::error::Error: Must include issue number and description after stack/feature name."
          fi